### ISSUE TITLE
Presets won't save

### ISSUE THREAD

**Issue by helloyanis** [Zutatensuppe/tetrio-preset#1]
![image](https://github.com/Zutatensuppe/tetrio-preset/assets/40769776/1ddf2180-fd4e-4397-9d2b-6c9bf7aecab9)
When I try saving a preset in a custom room

**Comment by Zutatensuppe** [comment]
@helloyanis hi, i updated the code, there were some changes since i last looked at tetr.io ^^ 
now presets should work again~!

(you need to create new ones, if you have existing ones, they won't work anymore)

**Comment by helloyanis** [comment]
Thank you! In the meantime [I made my own](https://github.com/helloyanis/tetr.io-custom-room-saver) that will soon be public on the Mozilla add-ons page when it gets reviewed, if you wanna try it out!
To try it in the meantime :
1. Code > Download and extract the zip
2. Open firefox and go to `about:debugging#/runtime/this-firefox`
3. Click on "Load temporary add-on"
4. Click on any file in the zip you extracted earlier
5. Go to tetr.io and there will be a new icon in the search bar
The add-on will be removed after you close the browser.

**Comment by Zutatensuppe** [comment]
oooh gud idea to make it an extension ^^
